# Generated by Django 4.1.7 on 2023-02-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_handler", "0002_auto_20230214_1657"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_logged_in",
            new_name="isLoggedIn",
        ),
    ]
