# Generated by Django 3.2.17 on 2023-02-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0003_rename_is_logged_in_user_isloggedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isLoggedIn',
        ),
    ]
